### ISSUE TITLE
Create the default pages

### ISSUE THREAD

**Issue by thomalexandre** [thomalexandre/qking4u#1]
**Profile page**
/web/app_dev.php/users/show/${id}       --> should show the profile of the user ${id} (not need to be logged)
/web/app_dev.php/users/edit/                   --> should edit the profile of the logged user (Only logged user)

**Dinner page**
/web/app_dev.php/dinners                        --> Show all dinner of the logged user (Only logged user)
/web/app_dev.php/dinner/show/${id}                        --> Show the related dinner
/web/app_dev.php/dinner/edit/${id}                        --> edit the dinner if Im the owner
/web/app_dev.php/dinner/create                      --> create a new dinner (If Im the owner)

**Search**
/web/app_dev.php/                                    --> Search page to serch for city and date
/web/app_dev.php/search/city/date           --> Search results > All related dinner

Not sure about all of this but it can be a start

**Comment by Szeki** [comment]
Default pages has been added. Unfortunately the UI is quite ugly...

**Comment by thomalexandre** [comment]
Ohh so you did some new pages 

I updated yesterday and saw the pages you did

Did you use API or more like fubwithbetting ?

It's cool was fast. No worry for the front end. It's not important right now

Will Check it tomorrow 

See you in Thursday

**Comment by Szeki** [comment]
First I tried to make it work, so I created like it was in FWB. Then I think we can start to refactor and create the APIs. Still the login API will be the hardest

**Comment by thomalexandre** [comment]
Ok good approche

LGTM -> look good to me :)
